// Action types
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const ADD_POST = "ADD_POST";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";

export const SET_COUNTRIES = "SET_COUNTRIES";

export const FETCH_UNIVERSITIES_REQUEST = "FETCH_UNIVERSITIES_REQUEST";
export const FETCH_UNIVERSITIES_SUCCESS = "FETCH_UNIVERSITIES_SUCCESS";
export const FETCH_UNIVERSITIES_FAILURE = "FETCH_UNIVERSITIES_FAILURE";

export const FETCH_ZIPCODE_REQUEST = "FETCH_ZIPCODE_REQUEST";
export const FETCH_ZIPCODE_SUCCESS = "FETCH_ZIPCODE_SUCCESS";
export const FETCH_ZIPCODE_FAILURE = "FETCH_ZIPCODE_FAILURE";
